version: '3.8'

services:
  red-pill:
    image: postgres:14.13-alpine3.20
    container_name: red-pill
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: